name: Python checks

on:
    push:
    pull_request:

jobs:
    flake8:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"
                  cache: "pip"
            - name: Install dependencies
              run: pip install -r requirements_dev.txt
            - name: Lint with flake8
              run: flake8 .
